default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>

development:
  <<: *default
  database: RoRPayments_development
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

test:
  <<: *default
  database: RoRPayments_test
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>


production:
  <<: *default
  database: RoRPayments_production
  username: RoRPayments
  password: <%= ENV["RORPAYMENTS_DATABASE_PASSWORD"] %>
